[package]
name = "bevy-inspector-egui"
version = "0.15.0-pre.0"
edition = "2021"
repository = "https://github.com/jakobhellermann/bevy-inspector-egui/"
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "Inspector plugin for the bevy game engine"
keywords = ["bevy", "inspector", "egui", "editor", "reflect"]
categories = ["game-development", "gui", "visualization", "development-tools::procedural-macro-helpers"]

[dependencies]
bevy-inspector-egui-derive = { version = "0.15.0-pre.0", path = "../bevy-inspector-egui-derive" }
bevy_reflect = { version = "0.9" }
bevy_ecs = { version = "0.9" }
bevy_app = { version = "0.9" }
bevy_asset = { version = "0.9" }
bevy_hierarchy = { version = "0.9" }
bevy_core = { version = "0.9" }
bevy_render = { version = "0.9" }
bevy_pbr = { version = "0.9" }
bevy_math = { version = "0.9" }
bevy_core_pipeline = { version = "0.9" }
bevy_utils = { version = "0.9" }

egui = "0.20.0"
bevy_egui = "0.17"

image = { version = "0.24.5", default-features = false }
once_cell = "1.16.0"
pretty-type-name = "1.0.0"
smallvec = "1.10.0"

[dev-dependencies]
bevy = { version = "0.9", default-features = false, features = ["render", "x11", "bevy_winit", "animation", "png"] }
egui_dock = { git = "https://github.com/Adanos020/egui_dock", rev = "041e5f362c281c286a63edeef2f7d02dbd5d62f4" }
egui-gizmo = "0.8"


[[example]]
name = "inspector_options"
path = "examples/basic/inspector_options.rs"

[[example]]
name = "resource_inspector"
path = "examples/quick/resource_inspector.rs"

[[example]]
name = "world_inspector"
path = "examples/quick/world_inspector.rs"

[[example]]
name = "world_inspector_assets"
path = "examples/quick/world_inspector_assets.rs"

[[example]]
name = "state_inspector"
path = "examples/quick/state_inspector.rs"

[[example]]
name = "egui_dock"
path = "examples/integrations/egui_dock.rs"

[[example]]
name = "side_panel"
path = "examples/integrations/side_panel.rs"
